### ISSUE TITLE
https://gene-info.org/workspace/ not coming up with anything

### ISSUE THREAD

**Issue by joreynajr** [knightjdr/gene-info#17]
### Gene-Info Box not popping up

**Steps to reproduce the behavior:**
1. Go to https://gene-info.org/workspace/
2. Copy-paste my gene list
3. Double-click
4. Nothing comes up, no error sign

![image](https://user-images.githubusercontent.com/14253227/155443025-49203a7d-4a83-41dc-83db-ca0199962973.png)

**Comment by knightjdr** [comment]
Can you provide a bit more information:

1) What browser are you using?
2) Have you changed any of the default settings?
3) When did you install the extension (roughly)?

**Comment by joreynajr** [comment]
For the extension I am using Google Chrome, I haven't changed any settings and I have re-installed the extension about a week ago. But I do have another question, I was thinking the website (https://gene-info.org/workspace/) could work without having to rely on the extension but the website alone doesn't seem to be working for me.

**Comment by joreynajr** [comment]
I tried turning off another extension that does some highlighting on website and I re-installed the extension and it seems to work. I guess I just have to be careful with extensions whose functions partially overlap?

**Comment by knightjdr** [comment]
It sounds like there may be some interference from another extension. It may be intercepting the double-click event and not allowing it to propagate. I'm going to close this issue because we can't address that on our end.

We don't intend on building the extension's features into the website itself. It's redundant and we don't have the time to prioritize something like that.

**Comment by joreynajr** [comment]
No problem! Thanks for the quick replies.
