### ISSUE TITLE
Fission yeast

### ISSUE THREAD

**Issue by ValWood** [knightjdr/gene-info#6]
Hi,
I love this. Is it possible to add for fission yeast and we will advertise to our community
(PomBase is one of the core GO contributing databases)
https://www.pombase.org/

Val

**Comment by knightjdr** [comment]
Thanks Val.

This looks straightforward. I don't know if I can have this in by our next release (March 15) but should be possible for April 15th.

I'm leaving some notes below for my own sake.

* species: Schizosaccharomyces pombe (ID: 284812)
* UniProt reviewed entries: : 5 141
* new IDs: PomBase (format, e.g. SPAC24B11.06c)
* external links: PomBase (https://www.pombase.org)
* AmiGO links: via PomBase ID

**Comment by ValWood** [comment]
Sounds good. 
You can get files of  all gene names from here:
https://www.pombase.org/downloads/names-and-identifiers
v

**Comment by knightjdr** [comment]
Is there a way to directly link to search results at Pombase?

For example, if I wanted to view all possible results for the term `test` is there a url like `https://www.pombase.org/query?test` to link to?

We're adding a new feature so that if someone makes a query and there is no match they can click on links to open search results at UniProt, NCBI, Ensembl and then any species-specific databases.

It's not a problem if there isn't I just wanted to include if possible.

**Comment by ValWood** [comment]
Well, we don't have an API (our users are mainly bench biologists and it is something that they never request), bus our developer  Kim @kimrutherford  might be able to advise. We can do "canned queries" but I don't know how this would translate into external queries. So at present is it possible we can only do single query links  for ontology terms
https://www.pombase.org/term/GO:0000502
rather than combination queries.

val

**Comment by kimrutherford** [comment]
> So at present is it possible we can only do single query links for ontology terms
> https://www.pombase.org/term/GO:0000502

That's the best bet at the moment if I'm understanding things.  Those links are stable and will always show all pombe annotation for any given term (and its descendants).  There are also links to publications: https://www.pombase.org/reference/PMID:20679485

We're looking for ways to improve the site so we're keen to hear about any changes that would be helpful.

**Comment by knightjdr** [comment]
It's okay if you don't have it setup.

I was just looking for something like this at UniProt: `https://www.uniprot.org/uniprot/?query=mapk`
that would show all results for the term `mapk`.

We can still use what you have for directly linking to your report pages, but in the case of terms we can't match we'll just link to UniProt, NCBI and Ensembl search listings.

Thanks.l

**Comment by knightjdr** [comment]
This is complete and should be online the week of April 15th.

It will be part of version 1.1.

You can go to chrome://extensions/ and check the version number there when the time comes (updates should happen automatically but if not just hit the "Update" button at the top).

**Comment by ValWood** [comment]
Do you have a nice standard blurb to describe that I can post to our user mailing list  (pombelist) to tell them about it? I can't remember how I came across it!

**Comment by knightjdr** [comment]
We don't have anything specific.

You can checkout our [homepage](https://gene-info.lunenfeld.ca) or BioGRID's [news item](https://thebiogrid.org/news/207) for a nice example of something similar.

**Comment by ValWood** [comment]
perfect!

**Comment by knightjdr** [comment]
These changes are now live.

**Comment by ValWood** [comment]
Hi James. I installed and I can't get it to  work for pombe. I am selecting genes and organism. I tried   drag and double click?

**Comment by ValWood** [comment]
...or cerevisiae 

Can you point be to some examples to test?

Thanks

Val

**Comment by knightjdr** [comment]
Hmm, can you show me what you are clicking on (page, text)? Are you getting an error or no match? An error should give a link to GitHub, no match should give links to UniProt, etc.

Leave autodetection on and you can click on any gene symbol or synonym, or supported accession (see the [docs](https://gene-info.org/#settings) for what's supported).

On your site, for example, https://www.pombase.org/gene/SPBC32F12.06, you can click on the gene standard name or the UniProt links will work but you'd have to drag them since clicking will trigger the link.

In fission yeast (https://www.yeastgenome.org/locus/YLR226W) you can click the standard name, systemic locus and aliases. None of the gene names in the description on this page work because of the trailing "p". The trailing "p" names aren't listed as aliases or official names. I'm not familiar with yeast naming conventions and whether we should be supporting this or not.

**Comment by kimrutherford** [comment]
Hi.  The extension works for pombe for me in Chrome and Firefox once I remembered to change the organism to "Schizosaccharomyces pombe".

Thanks!

**Comment by ValWood** [comment]
OK I think I wasn't waiting long enough for the pop up/ and or chrome was out of date. It now works for me. Thanks.
