### ISSUE TITLE
Can only select one GO aspect at once/ GO not working for pombe

### ISSUE THREAD

**Issue by ValWood** [knightjdr/gene-info#8]
**GO aspect is restricted to a single aspect**
* It would be much better to be able to see all 3 simultaneously

(also the GO feature does not seem to work for pombe gene identifiers- all pombe genes are in the GO database)

**Comment by ValWood** [comment]
also Pfam does not show

I see this 👎 
![cdr1](https://user-images.githubusercontent.com/7359272/56049984-9aeda100-5d42-11e9-90af-45a3772f30c0.jpg)

rather than this:
https://thebiogrid.org/news/207
which is much richer.

**Comment by knightjdr** [comment]
1. GO namespace
Genes can have a lot of GO terms so during testing we decided on separating the display into three and have users click between them. I don't think this will change.

2. GO feature does not seem to work for pombe gene identifiers
What do you mean by GO feature? GO terms don't show or the link doesn't work? You'll have to provide me with examples and details of exactly what you are doing so that I can diagnose because all the ones I have looked are working.

3. Pfam doesn't show
In the image there is a link to Pfam, so not sure what you mean here.

4. https://thebiogrid.org/news/207 is richer
That is the detailed (and default) report view. It looks like you switched to tooltip mode which is why you are only being offered links. Click on the extension icon and under "Display options" select "detailed report".

**Comment by ValWood** [comment]
OK got it!
